### ISSUE TITLE
LVQ Database Request

### ISSUE THREAD

**Issue by cheunglaihip** [zakopz/LVQ_Database#2]
Dear professor,the download link provided in the github is currently inaccessible. Could you please provide me with an alternative link to download the database?

**Comment by cheunglaihip** [comment]
![Uploading NOTFOUND.png…]()

**Comment by cheunglaihip** [comment]
Not Found
The requested URL was not found on this server.

Apache/2.4.41 (Ubuntu) Server at 192.168.46.153 Port 80

**Comment by cheunglaihip** [comment]
Not Found
The requested URL was not found on this server.

**Comment by zakopz** [comment]
Hello.. here is the alternative link for download [link](https://mega.nz/file/q4VSSRZT#Yl56O1EpR_2nPn-zFoz2O5tFqhw6JrJB-yACELa7hjE)
